# Autogenerated using ProtoBuf.jl v1.2.0 on 2026-01-10T11:38:24.927
# original file: /home/scelles-admin/.julia/packages/ProtoBuf/vW0fR/src/google/protobuf/empty.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Empty


struct Empty end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Empty})
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return Empty()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Empty)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Empty)
    encoded_size = 0
    return encoded_size
end
