# Autogenerated using ProtoBuf.jl v1.3.0
# original file: google/protobuf/empty.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export Empty


struct Empty end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Empty}, _endpos::Int=0, _group::Bool=false)
    while !PB.message_done(d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return Empty()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Empty)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Empty)
    encoded_size = 0
    return encoded_size
end
