# Autogenerated using ProtoBuf.jl v1.2.0 on 2026-01-10T11:38:24.397
# original file: /home/scelles-admin/.julia/artifacts/c90104a6945c9e4b68315984a83d31d012ee8abc/pulumi/callback.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export CallbackInvokeRequest, Callback, CallbackInvokeResponse


struct CallbackInvokeRequest
    token::String
    request::Vector{UInt8}
end
PB.default_values(::Type{CallbackInvokeRequest}) = (;token = "", request = UInt8[])
PB.field_numbers(::Type{CallbackInvokeRequest}) = (;token = 1, request = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CallbackInvokeRequest})
    token = ""
    request = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            token = PB.decode(d, String)
        elseif field_number == 2
            request = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return CallbackInvokeRequest(token, request)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CallbackInvokeRequest)
    initpos = position(e.io)
    !isempty(x.token) && PB.encode(e, 1, x.token)
    !isempty(x.request) && PB.encode(e, 2, x.request)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CallbackInvokeRequest)
    encoded_size = 0
    !isempty(x.token) && (encoded_size += PB._encoded_size(x.token, 1))
    !isempty(x.request) && (encoded_size += PB._encoded_size(x.request, 2))
    return encoded_size
end

struct Callback
    target::String
    token::String
end
PB.default_values(::Type{Callback}) = (;target = "", token = "")
PB.field_numbers(::Type{Callback}) = (;target = 1, token = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Callback})
    target = ""
    token = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            target = PB.decode(d, String)
        elseif field_number == 2
            token = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return Callback(target, token)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Callback)
    initpos = position(e.io)
    !isempty(x.target) && PB.encode(e, 1, x.target)
    !isempty(x.token) && PB.encode(e, 2, x.token)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Callback)
    encoded_size = 0
    !isempty(x.target) && (encoded_size += PB._encoded_size(x.target, 1))
    !isempty(x.token) && (encoded_size += PB._encoded_size(x.token, 2))
    return encoded_size
end

struct CallbackInvokeResponse
    response::Vector{UInt8}
end
PB.default_values(::Type{CallbackInvokeResponse}) = (;response = UInt8[])
PB.field_numbers(::Type{CallbackInvokeResponse}) = (;response = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:CallbackInvokeResponse})
    response = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            response = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return CallbackInvokeResponse(response)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::CallbackInvokeResponse)
    initpos = position(e.io)
    !isempty(x.response) && PB.encode(e, 1, x.response)
    return position(e.io) - initpos
end
function PB._encoded_size(x::CallbackInvokeResponse)
    encoded_size = 0
    !isempty(x.response) && (encoded_size += PB._encoded_size(x.response, 1))
    return encoded_size
end

# TODO: SERVICE
#    Callbacks
