# Autogenerated using ProtoBuf.jl v1.2.0 on 2026-01-10T11:38:24.095
# original file: /home/scelles-admin/.julia/artifacts/c90104a6945c9e4b68315984a83d31d012ee8abc/engine.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export LogSeverity, StartDebuggingRequest, GetRootResourceResponse, SetRootResourceRequest
export GetRootResourceRequest, SetRootResourceResponse, LogRequest


@enumx LogSeverity DEBUG=0 INFO=1 WARNING=2 ERROR=3

struct StartDebuggingRequest
    config::Union{Nothing,google.protobuf.Struct}
    message::String
end
PB.default_values(::Type{StartDebuggingRequest}) = (;config = nothing, message = "")
PB.field_numbers(::Type{StartDebuggingRequest}) = (;config = 1, message = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:StartDebuggingRequest})
    config = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    message = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, config)
        elseif field_number == 2
            message = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return StartDebuggingRequest(config[], message)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::StartDebuggingRequest)
    initpos = position(e.io)
    !isnothing(x.config) && PB.encode(e, 1, x.config)
    !isempty(x.message) && PB.encode(e, 2, x.message)
    return position(e.io) - initpos
end
function PB._encoded_size(x::StartDebuggingRequest)
    encoded_size = 0
    !isnothing(x.config) && (encoded_size += PB._encoded_size(x.config, 1))
    !isempty(x.message) && (encoded_size += PB._encoded_size(x.message, 2))
    return encoded_size
end

struct GetRootResourceResponse
    urn::String
end
PB.default_values(::Type{GetRootResourceResponse}) = (;urn = "")
PB.field_numbers(::Type{GetRootResourceResponse}) = (;urn = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:GetRootResourceResponse})
    urn = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            urn = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return GetRootResourceResponse(urn)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::GetRootResourceResponse)
    initpos = position(e.io)
    !isempty(x.urn) && PB.encode(e, 1, x.urn)
    return position(e.io) - initpos
end
function PB._encoded_size(x::GetRootResourceResponse)
    encoded_size = 0
    !isempty(x.urn) && (encoded_size += PB._encoded_size(x.urn, 1))
    return encoded_size
end

struct SetRootResourceRequest
    urn::String
end
PB.default_values(::Type{SetRootResourceRequest}) = (;urn = "")
PB.field_numbers(::Type{SetRootResourceRequest}) = (;urn = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetRootResourceRequest})
    urn = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            urn = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return SetRootResourceRequest(urn)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetRootResourceRequest)
    initpos = position(e.io)
    !isempty(x.urn) && PB.encode(e, 1, x.urn)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetRootResourceRequest)
    encoded_size = 0
    !isempty(x.urn) && (encoded_size += PB._encoded_size(x.urn, 1))
    return encoded_size
end

struct GetRootResourceRequest end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:GetRootResourceRequest})
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return GetRootResourceRequest()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::GetRootResourceRequest)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::GetRootResourceRequest)
    encoded_size = 0
    return encoded_size
end

struct SetRootResourceResponse end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SetRootResourceResponse})
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return SetRootResourceResponse()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SetRootResourceResponse)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SetRootResourceResponse)
    encoded_size = 0
    return encoded_size
end

struct LogRequest
    severity::LogSeverity.T
    message::String
    urn::String
    streamId::Int32
    ephemeral::Bool
end
PB.default_values(::Type{LogRequest}) = (;severity = LogSeverity.DEBUG, message = "", urn = "", streamId = zero(Int32), ephemeral = false)
PB.field_numbers(::Type{LogRequest}) = (;severity = 1, message = 2, urn = 3, streamId = 4, ephemeral = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:LogRequest})
    severity = LogSeverity.DEBUG
    message = ""
    urn = ""
    streamId = zero(Int32)
    ephemeral = false
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            severity = PB.decode(d, LogSeverity.T)
        elseif field_number == 2
            message = PB.decode(d, String)
        elseif field_number == 3
            urn = PB.decode(d, String)
        elseif field_number == 4
            streamId = PB.decode(d, Int32)
        elseif field_number == 5
            ephemeral = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return LogRequest(severity, message, urn, streamId, ephemeral)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::LogRequest)
    initpos = position(e.io)
    x.severity != LogSeverity.DEBUG && PB.encode(e, 1, x.severity)
    !isempty(x.message) && PB.encode(e, 2, x.message)
    !isempty(x.urn) && PB.encode(e, 3, x.urn)
    x.streamId != zero(Int32) && PB.encode(e, 4, x.streamId)
    x.ephemeral != false && PB.encode(e, 5, x.ephemeral)
    return position(e.io) - initpos
end
function PB._encoded_size(x::LogRequest)
    encoded_size = 0
    x.severity != LogSeverity.DEBUG && (encoded_size += PB._encoded_size(x.severity, 1))
    !isempty(x.message) && (encoded_size += PB._encoded_size(x.message, 2))
    !isempty(x.urn) && (encoded_size += PB._encoded_size(x.urn, 3))
    x.streamId != zero(Int32) && (encoded_size += PB._encoded_size(x.streamId, 4))
    x.ephemeral != false && (encoded_size += PB._encoded_size(x.ephemeral, 5))
    return encoded_size
end

# TODO: SERVICE
#    Engine
