# Autogenerated using ProtoBuf.jl v1.2.0 on 2026-01-10T11:23:19.769
# original file: /home/scelles-admin/.julia/dev/Pulumi/proto/resource.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export ResourceHookResponse, ResourceHookRequest, RegisterResourceHookRequest
export RegisterPackageResponse, Parameterization, SupportsFeatureRequest
export var"RegisterResourceRequest.ResourceHooksBinding", ResourceInvokeRequest
export ReadResourceRequest, Result, var"ResourceCallRequest.ArgumentDependencies"
export SupportsFeatureResponse, RegisterResourceOutputsRequest, ReadResourceResponse
export var"RegisterResourceResponse.PropertyDependencies"
export var"RegisterResourceRequest.PropertyDependencies"
export var"RegisterResourceRequest.CustomTimeouts", TransformInvokeOptions
export RegisterPackageRequest, ResourceCallRequest, RegisterResourceResponse
export TransformResourceOptions, RegisterResourceRequest, TransformInvokeResponse
export TransformInvokeRequest, TransformResponse, TransformRequest


struct ResourceHookResponse
    error::String
end
PB.default_values(::Type{ResourceHookResponse}) = (;error = "")
PB.field_numbers(::Type{ResourceHookResponse}) = (;error = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResourceHookResponse})
    error = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            error = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return ResourceHookResponse(error)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResourceHookResponse)
    initpos = position(e.io)
    !isempty(x.error) && PB.encode(e, 1, x.error)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResourceHookResponse)
    encoded_size = 0
    !isempty(x.error) && (encoded_size += PB._encoded_size(x.error, 1))
    return encoded_size
end

struct ResourceHookRequest
    urn::String
    id::String
    name::String
    var"#type"::String
    new_inputs::Union{Nothing,google.protobuf.Struct}
    old_inputs::Union{Nothing,google.protobuf.Struct}
    new_outputs::Union{Nothing,google.protobuf.Struct}
    old_outputs::Union{Nothing,google.protobuf.Struct}
end
PB.default_values(::Type{ResourceHookRequest}) = (;urn = "", id = "", name = "", var"#type" = "", new_inputs = nothing, old_inputs = nothing, new_outputs = nothing, old_outputs = nothing)
PB.field_numbers(::Type{ResourceHookRequest}) = (;urn = 1, id = 2, name = 3, var"#type" = 4, new_inputs = 5, old_inputs = 6, new_outputs = 7, old_outputs = 8)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResourceHookRequest})
    urn = ""
    id = ""
    name = ""
    var"#type" = ""
    new_inputs = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    old_inputs = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    new_outputs = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    old_outputs = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            urn = PB.decode(d, String)
        elseif field_number == 2
            id = PB.decode(d, String)
        elseif field_number == 3
            name = PB.decode(d, String)
        elseif field_number == 4
            var"#type" = PB.decode(d, String)
        elseif field_number == 5
            PB.decode!(d, new_inputs)
        elseif field_number == 6
            PB.decode!(d, old_inputs)
        elseif field_number == 7
            PB.decode!(d, new_outputs)
        elseif field_number == 8
            PB.decode!(d, old_outputs)
        else
            Base.skip(d, wire_type)
        end
    end
    return ResourceHookRequest(urn, id, name, var"#type", new_inputs[], old_inputs[], new_outputs[], old_outputs[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResourceHookRequest)
    initpos = position(e.io)
    !isempty(x.urn) && PB.encode(e, 1, x.urn)
    !isempty(x.id) && PB.encode(e, 2, x.id)
    !isempty(x.name) && PB.encode(e, 3, x.name)
    !isempty(x.var"#type") && PB.encode(e, 4, x.var"#type")
    !isnothing(x.new_inputs) && PB.encode(e, 5, x.new_inputs)
    !isnothing(x.old_inputs) && PB.encode(e, 6, x.old_inputs)
    !isnothing(x.new_outputs) && PB.encode(e, 7, x.new_outputs)
    !isnothing(x.old_outputs) && PB.encode(e, 8, x.old_outputs)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResourceHookRequest)
    encoded_size = 0
    !isempty(x.urn) && (encoded_size += PB._encoded_size(x.urn, 1))
    !isempty(x.id) && (encoded_size += PB._encoded_size(x.id, 2))
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 3))
    !isempty(x.var"#type") && (encoded_size += PB._encoded_size(x.var"#type", 4))
    !isnothing(x.new_inputs) && (encoded_size += PB._encoded_size(x.new_inputs, 5))
    !isnothing(x.old_inputs) && (encoded_size += PB._encoded_size(x.old_inputs, 6))
    !isnothing(x.new_outputs) && (encoded_size += PB._encoded_size(x.new_outputs, 7))
    !isnothing(x.old_outputs) && (encoded_size += PB._encoded_size(x.old_outputs, 8))
    return encoded_size
end

struct RegisterResourceHookRequest
    name::String
    callback::Union{Nothing,Callback}
    on_dry_run::Bool
end
PB.default_values(::Type{RegisterResourceHookRequest}) = (;name = "", callback = nothing, on_dry_run = false)
PB.field_numbers(::Type{RegisterResourceHookRequest}) = (;name = 1, callback = 2, on_dry_run = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RegisterResourceHookRequest})
    name = ""
    callback = Ref{Union{Nothing,Callback}}(nothing)
    on_dry_run = false
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, callback)
        elseif field_number == 3
            on_dry_run = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return RegisterResourceHookRequest(name, callback[], on_dry_run)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RegisterResourceHookRequest)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isnothing(x.callback) && PB.encode(e, 2, x.callback)
    x.on_dry_run != false && PB.encode(e, 3, x.on_dry_run)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RegisterResourceHookRequest)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isnothing(x.callback) && (encoded_size += PB._encoded_size(x.callback, 2))
    x.on_dry_run != false && (encoded_size += PB._encoded_size(x.on_dry_run, 3))
    return encoded_size
end

struct RegisterPackageResponse
    ref::String
end
PB.default_values(::Type{RegisterPackageResponse}) = (;ref = "")
PB.field_numbers(::Type{RegisterPackageResponse}) = (;ref = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RegisterPackageResponse})
    ref = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            ref = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return RegisterPackageResponse(ref)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RegisterPackageResponse)
    initpos = position(e.io)
    !isempty(x.ref) && PB.encode(e, 1, x.ref)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RegisterPackageResponse)
    encoded_size = 0
    !isempty(x.ref) && (encoded_size += PB._encoded_size(x.ref, 1))
    return encoded_size
end

struct Parameterization
    name::String
    version::String
    value::Vector{UInt8}
end
PB.default_values(::Type{Parameterization}) = (;name = "", version = "", value = UInt8[])
PB.field_numbers(::Type{Parameterization}) = (;name = 1, version = 2, value = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Parameterization})
    name = ""
    version = ""
    value = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            version = PB.decode(d, String)
        elseif field_number == 3
            value = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return Parameterization(name, version, value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Parameterization)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.version) && PB.encode(e, 2, x.version)
    !isempty(x.value) && PB.encode(e, 3, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Parameterization)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 2))
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 3))
    return encoded_size
end

struct SupportsFeatureRequest
    id::String
end
PB.default_values(::Type{SupportsFeatureRequest}) = (;id = "")
PB.field_numbers(::Type{SupportsFeatureRequest}) = (;id = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SupportsFeatureRequest})
    id = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return SupportsFeatureRequest(id)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SupportsFeatureRequest)
    initpos = position(e.io)
    !isempty(x.id) && PB.encode(e, 1, x.id)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SupportsFeatureRequest)
    encoded_size = 0
    !isempty(x.id) && (encoded_size += PB._encoded_size(x.id, 1))
    return encoded_size
end

struct var"RegisterResourceRequest.ResourceHooksBinding"
    before_create::Vector{String}
    after_create::Vector{String}
    before_update::Vector{String}
    after_update::Vector{String}
    before_delete::Vector{String}
    after_delete::Vector{String}
end
PB.default_values(::Type{var"RegisterResourceRequest.ResourceHooksBinding"}) = (;before_create = Vector{String}(), after_create = Vector{String}(), before_update = Vector{String}(), after_update = Vector{String}(), before_delete = Vector{String}(), after_delete = Vector{String}())
PB.field_numbers(::Type{var"RegisterResourceRequest.ResourceHooksBinding"}) = (;before_create = 1, after_create = 2, before_update = 3, after_update = 4, before_delete = 5, after_delete = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"RegisterResourceRequest.ResourceHooksBinding"})
    before_create = PB.BufferedVector{String}()
    after_create = PB.BufferedVector{String}()
    before_update = PB.BufferedVector{String}()
    after_update = PB.BufferedVector{String}()
    before_delete = PB.BufferedVector{String}()
    after_delete = PB.BufferedVector{String}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, before_create)
        elseif field_number == 2
            PB.decode!(d, after_create)
        elseif field_number == 3
            PB.decode!(d, before_update)
        elseif field_number == 4
            PB.decode!(d, after_update)
        elseif field_number == 5
            PB.decode!(d, before_delete)
        elseif field_number == 6
            PB.decode!(d, after_delete)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"RegisterResourceRequest.ResourceHooksBinding"(before_create[], after_create[], before_update[], after_update[], before_delete[], after_delete[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"RegisterResourceRequest.ResourceHooksBinding")
    initpos = position(e.io)
    !isempty(x.before_create) && PB.encode(e, 1, x.before_create)
    !isempty(x.after_create) && PB.encode(e, 2, x.after_create)
    !isempty(x.before_update) && PB.encode(e, 3, x.before_update)
    !isempty(x.after_update) && PB.encode(e, 4, x.after_update)
    !isempty(x.before_delete) && PB.encode(e, 5, x.before_delete)
    !isempty(x.after_delete) && PB.encode(e, 6, x.after_delete)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"RegisterResourceRequest.ResourceHooksBinding")
    encoded_size = 0
    !isempty(x.before_create) && (encoded_size += PB._encoded_size(x.before_create, 1))
    !isempty(x.after_create) && (encoded_size += PB._encoded_size(x.after_create, 2))
    !isempty(x.before_update) && (encoded_size += PB._encoded_size(x.before_update, 3))
    !isempty(x.after_update) && (encoded_size += PB._encoded_size(x.after_update, 4))
    !isempty(x.before_delete) && (encoded_size += PB._encoded_size(x.before_delete, 5))
    !isempty(x.after_delete) && (encoded_size += PB._encoded_size(x.after_delete, 6))
    return encoded_size
end

struct ResourceInvokeRequest
    tok::String
    args::Union{Nothing,google.protobuf.Struct}
    provider::String
    version::String
    acceptResources::Bool
    pluginDownloadURL::String
    pluginChecksums::Dict{String,Vector{UInt8}}
    sourcePosition::Union{Nothing,SourcePosition}
    stackTrace::Union{Nothing,StackTrace}
    parentStackTraceHandle::String
    packageRef::String
end
PB.default_values(::Type{ResourceInvokeRequest}) = (;tok = "", args = nothing, provider = "", version = "", acceptResources = false, pluginDownloadURL = "", pluginChecksums = Dict{String,Vector{UInt8}}(), sourcePosition = nothing, stackTrace = nothing, parentStackTraceHandle = "", packageRef = "")
PB.field_numbers(::Type{ResourceInvokeRequest}) = (;tok = 1, args = 2, provider = 3, version = 4, acceptResources = 5, pluginDownloadURL = 6, pluginChecksums = 8, sourcePosition = 7, stackTrace = 10, parentStackTraceHandle = 11, packageRef = 9)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResourceInvokeRequest})
    tok = ""
    args = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    provider = ""
    version = ""
    acceptResources = false
    pluginDownloadURL = ""
    pluginChecksums = Dict{String,Vector{UInt8}}()
    sourcePosition = Ref{Union{Nothing,SourcePosition}}(nothing)
    stackTrace = Ref{Union{Nothing,StackTrace}}(nothing)
    parentStackTraceHandle = ""
    packageRef = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            tok = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, args)
        elseif field_number == 3
            provider = PB.decode(d, String)
        elseif field_number == 4
            version = PB.decode(d, String)
        elseif field_number == 5
            acceptResources = PB.decode(d, Bool)
        elseif field_number == 6
            pluginDownloadURL = PB.decode(d, String)
        elseif field_number == 8
            PB.decode!(d, pluginChecksums)
        elseif field_number == 7
            PB.decode!(d, sourcePosition)
        elseif field_number == 10
            PB.decode!(d, stackTrace)
        elseif field_number == 11
            parentStackTraceHandle = PB.decode(d, String)
        elseif field_number == 9
            packageRef = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return ResourceInvokeRequest(tok, args[], provider, version, acceptResources, pluginDownloadURL, pluginChecksums, sourcePosition[], stackTrace[], parentStackTraceHandle, packageRef)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResourceInvokeRequest)
    initpos = position(e.io)
    !isempty(x.tok) && PB.encode(e, 1, x.tok)
    !isnothing(x.args) && PB.encode(e, 2, x.args)
    !isempty(x.provider) && PB.encode(e, 3, x.provider)
    !isempty(x.version) && PB.encode(e, 4, x.version)
    x.acceptResources != false && PB.encode(e, 5, x.acceptResources)
    !isempty(x.pluginDownloadURL) && PB.encode(e, 6, x.pluginDownloadURL)
    !isempty(x.pluginChecksums) && PB.encode(e, 8, x.pluginChecksums)
    !isnothing(x.sourcePosition) && PB.encode(e, 7, x.sourcePosition)
    !isnothing(x.stackTrace) && PB.encode(e, 10, x.stackTrace)
    !isempty(x.parentStackTraceHandle) && PB.encode(e, 11, x.parentStackTraceHandle)
    !isempty(x.packageRef) && PB.encode(e, 9, x.packageRef)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResourceInvokeRequest)
    encoded_size = 0
    !isempty(x.tok) && (encoded_size += PB._encoded_size(x.tok, 1))
    !isnothing(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    !isempty(x.provider) && (encoded_size += PB._encoded_size(x.provider, 3))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 4))
    x.acceptResources != false && (encoded_size += PB._encoded_size(x.acceptResources, 5))
    !isempty(x.pluginDownloadURL) && (encoded_size += PB._encoded_size(x.pluginDownloadURL, 6))
    !isempty(x.pluginChecksums) && (encoded_size += PB._encoded_size(x.pluginChecksums, 8))
    !isnothing(x.sourcePosition) && (encoded_size += PB._encoded_size(x.sourcePosition, 7))
    !isnothing(x.stackTrace) && (encoded_size += PB._encoded_size(x.stackTrace, 10))
    !isempty(x.parentStackTraceHandle) && (encoded_size += PB._encoded_size(x.parentStackTraceHandle, 11))
    !isempty(x.packageRef) && (encoded_size += PB._encoded_size(x.packageRef, 9))
    return encoded_size
end

struct ReadResourceRequest
    id::String
    var"#type"::String
    name::String
    parent::String
    properties::Union{Nothing,google.protobuf.Struct}
    dependencies::Vector{String}
    provider::String
    version::String
    acceptSecrets::Bool
    additionalSecretOutputs::Vector{String}
    acceptResources::Bool
    pluginDownloadURL::String
    pluginChecksums::Dict{String,Vector{UInt8}}
    sourcePosition::Union{Nothing,SourcePosition}
    stackTrace::Union{Nothing,StackTrace}
    parentStackTraceHandle::String
    packageRef::String
end
PB.reserved_fields(::Type{ReadResourceRequest}) = (names = ["aliases"], numbers = Union{Int,UnitRange{Int}}[11])
PB.default_values(::Type{ReadResourceRequest}) = (;id = "", var"#type" = "", name = "", parent = "", properties = nothing, dependencies = Vector{String}(), provider = "", version = "", acceptSecrets = false, additionalSecretOutputs = Vector{String}(), acceptResources = false, pluginDownloadURL = "", pluginChecksums = Dict{String,Vector{UInt8}}(), sourcePosition = nothing, stackTrace = nothing, parentStackTraceHandle = "", packageRef = "")
PB.field_numbers(::Type{ReadResourceRequest}) = (;id = 1, var"#type" = 2, name = 3, parent = 4, properties = 5, dependencies = 6, provider = 7, version = 8, acceptSecrets = 9, additionalSecretOutputs = 10, acceptResources = 12, pluginDownloadURL = 13, pluginChecksums = 15, sourcePosition = 14, stackTrace = 17, parentStackTraceHandle = 18, packageRef = 16)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ReadResourceRequest})
    id = ""
    var"#type" = ""
    name = ""
    parent = ""
    properties = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    dependencies = PB.BufferedVector{String}()
    provider = ""
    version = ""
    acceptSecrets = false
    additionalSecretOutputs = PB.BufferedVector{String}()
    acceptResources = false
    pluginDownloadURL = ""
    pluginChecksums = Dict{String,Vector{UInt8}}()
    sourcePosition = Ref{Union{Nothing,SourcePosition}}(nothing)
    stackTrace = Ref{Union{Nothing,StackTrace}}(nothing)
    parentStackTraceHandle = ""
    packageRef = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, String)
        elseif field_number == 2
            var"#type" = PB.decode(d, String)
        elseif field_number == 3
            name = PB.decode(d, String)
        elseif field_number == 4
            parent = PB.decode(d, String)
        elseif field_number == 5
            PB.decode!(d, properties)
        elseif field_number == 6
            PB.decode!(d, dependencies)
        elseif field_number == 7
            provider = PB.decode(d, String)
        elseif field_number == 8
            version = PB.decode(d, String)
        elseif field_number == 9
            acceptSecrets = PB.decode(d, Bool)
        elseif field_number == 10
            PB.decode!(d, additionalSecretOutputs)
        elseif field_number == 12
            acceptResources = PB.decode(d, Bool)
        elseif field_number == 13
            pluginDownloadURL = PB.decode(d, String)
        elseif field_number == 15
            PB.decode!(d, pluginChecksums)
        elseif field_number == 14
            PB.decode!(d, sourcePosition)
        elseif field_number == 17
            PB.decode!(d, stackTrace)
        elseif field_number == 18
            parentStackTraceHandle = PB.decode(d, String)
        elseif field_number == 16
            packageRef = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return ReadResourceRequest(id, var"#type", name, parent, properties[], dependencies[], provider, version, acceptSecrets, additionalSecretOutputs[], acceptResources, pluginDownloadURL, pluginChecksums, sourcePosition[], stackTrace[], parentStackTraceHandle, packageRef)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ReadResourceRequest)
    initpos = position(e.io)
    !isempty(x.id) && PB.encode(e, 1, x.id)
    !isempty(x.var"#type") && PB.encode(e, 2, x.var"#type")
    !isempty(x.name) && PB.encode(e, 3, x.name)
    !isempty(x.parent) && PB.encode(e, 4, x.parent)
    !isnothing(x.properties) && PB.encode(e, 5, x.properties)
    !isempty(x.dependencies) && PB.encode(e, 6, x.dependencies)
    !isempty(x.provider) && PB.encode(e, 7, x.provider)
    !isempty(x.version) && PB.encode(e, 8, x.version)
    x.acceptSecrets != false && PB.encode(e, 9, x.acceptSecrets)
    !isempty(x.additionalSecretOutputs) && PB.encode(e, 10, x.additionalSecretOutputs)
    x.acceptResources != false && PB.encode(e, 12, x.acceptResources)
    !isempty(x.pluginDownloadURL) && PB.encode(e, 13, x.pluginDownloadURL)
    !isempty(x.pluginChecksums) && PB.encode(e, 15, x.pluginChecksums)
    !isnothing(x.sourcePosition) && PB.encode(e, 14, x.sourcePosition)
    !isnothing(x.stackTrace) && PB.encode(e, 17, x.stackTrace)
    !isempty(x.parentStackTraceHandle) && PB.encode(e, 18, x.parentStackTraceHandle)
    !isempty(x.packageRef) && PB.encode(e, 16, x.packageRef)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ReadResourceRequest)
    encoded_size = 0
    !isempty(x.id) && (encoded_size += PB._encoded_size(x.id, 1))
    !isempty(x.var"#type") && (encoded_size += PB._encoded_size(x.var"#type", 2))
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 3))
    !isempty(x.parent) && (encoded_size += PB._encoded_size(x.parent, 4))
    !isnothing(x.properties) && (encoded_size += PB._encoded_size(x.properties, 5))
    !isempty(x.dependencies) && (encoded_size += PB._encoded_size(x.dependencies, 6))
    !isempty(x.provider) && (encoded_size += PB._encoded_size(x.provider, 7))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 8))
    x.acceptSecrets != false && (encoded_size += PB._encoded_size(x.acceptSecrets, 9))
    !isempty(x.additionalSecretOutputs) && (encoded_size += PB._encoded_size(x.additionalSecretOutputs, 10))
    x.acceptResources != false && (encoded_size += PB._encoded_size(x.acceptResources, 12))
    !isempty(x.pluginDownloadURL) && (encoded_size += PB._encoded_size(x.pluginDownloadURL, 13))
    !isempty(x.pluginChecksums) && (encoded_size += PB._encoded_size(x.pluginChecksums, 15))
    !isnothing(x.sourcePosition) && (encoded_size += PB._encoded_size(x.sourcePosition, 14))
    !isnothing(x.stackTrace) && (encoded_size += PB._encoded_size(x.stackTrace, 17))
    !isempty(x.parentStackTraceHandle) && (encoded_size += PB._encoded_size(x.parentStackTraceHandle, 18))
    !isempty(x.packageRef) && (encoded_size += PB._encoded_size(x.packageRef, 16))
    return encoded_size
end

@enumx Result SUCCESS=0 FAIL=1 SKIP=2

struct var"ResourceCallRequest.ArgumentDependencies"
    urns::Vector{String}
end
PB.default_values(::Type{var"ResourceCallRequest.ArgumentDependencies"}) = (;urns = Vector{String}())
PB.field_numbers(::Type{var"ResourceCallRequest.ArgumentDependencies"}) = (;urns = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"ResourceCallRequest.ArgumentDependencies"})
    urns = PB.BufferedVector{String}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, urns)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"ResourceCallRequest.ArgumentDependencies"(urns[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"ResourceCallRequest.ArgumentDependencies")
    initpos = position(e.io)
    !isempty(x.urns) && PB.encode(e, 1, x.urns)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"ResourceCallRequest.ArgumentDependencies")
    encoded_size = 0
    !isempty(x.urns) && (encoded_size += PB._encoded_size(x.urns, 1))
    return encoded_size
end

struct SupportsFeatureResponse
    hasSupport::Bool
end
PB.default_values(::Type{SupportsFeatureResponse}) = (;hasSupport = false)
PB.field_numbers(::Type{SupportsFeatureResponse}) = (;hasSupport = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SupportsFeatureResponse})
    hasSupport = false
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            hasSupport = PB.decode(d, Bool)
        else
            Base.skip(d, wire_type)
        end
    end
    return SupportsFeatureResponse(hasSupport)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SupportsFeatureResponse)
    initpos = position(e.io)
    x.hasSupport != false && PB.encode(e, 1, x.hasSupport)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SupportsFeatureResponse)
    encoded_size = 0
    x.hasSupport != false && (encoded_size += PB._encoded_size(x.hasSupport, 1))
    return encoded_size
end

struct RegisterResourceOutputsRequest
    urn::String
    outputs::Union{Nothing,google.protobuf.Struct}
end
PB.default_values(::Type{RegisterResourceOutputsRequest}) = (;urn = "", outputs = nothing)
PB.field_numbers(::Type{RegisterResourceOutputsRequest}) = (;urn = 1, outputs = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RegisterResourceOutputsRequest})
    urn = ""
    outputs = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            urn = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, outputs)
        else
            Base.skip(d, wire_type)
        end
    end
    return RegisterResourceOutputsRequest(urn, outputs[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RegisterResourceOutputsRequest)
    initpos = position(e.io)
    !isempty(x.urn) && PB.encode(e, 1, x.urn)
    !isnothing(x.outputs) && PB.encode(e, 2, x.outputs)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RegisterResourceOutputsRequest)
    encoded_size = 0
    !isempty(x.urn) && (encoded_size += PB._encoded_size(x.urn, 1))
    !isnothing(x.outputs) && (encoded_size += PB._encoded_size(x.outputs, 2))
    return encoded_size
end

struct ReadResourceResponse
    urn::String
    properties::Union{Nothing,google.protobuf.Struct}
end
PB.default_values(::Type{ReadResourceResponse}) = (;urn = "", properties = nothing)
PB.field_numbers(::Type{ReadResourceResponse}) = (;urn = 1, properties = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ReadResourceResponse})
    urn = ""
    properties = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            urn = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, properties)
        else
            Base.skip(d, wire_type)
        end
    end
    return ReadResourceResponse(urn, properties[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ReadResourceResponse)
    initpos = position(e.io)
    !isempty(x.urn) && PB.encode(e, 1, x.urn)
    !isnothing(x.properties) && PB.encode(e, 2, x.properties)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ReadResourceResponse)
    encoded_size = 0
    !isempty(x.urn) && (encoded_size += PB._encoded_size(x.urn, 1))
    !isnothing(x.properties) && (encoded_size += PB._encoded_size(x.properties, 2))
    return encoded_size
end

struct var"RegisterResourceResponse.PropertyDependencies"
    urns::Vector{String}
end
PB.default_values(::Type{var"RegisterResourceResponse.PropertyDependencies"}) = (;urns = Vector{String}())
PB.field_numbers(::Type{var"RegisterResourceResponse.PropertyDependencies"}) = (;urns = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"RegisterResourceResponse.PropertyDependencies"})
    urns = PB.BufferedVector{String}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, urns)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"RegisterResourceResponse.PropertyDependencies"(urns[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"RegisterResourceResponse.PropertyDependencies")
    initpos = position(e.io)
    !isempty(x.urns) && PB.encode(e, 1, x.urns)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"RegisterResourceResponse.PropertyDependencies")
    encoded_size = 0
    !isempty(x.urns) && (encoded_size += PB._encoded_size(x.urns, 1))
    return encoded_size
end

struct var"RegisterResourceRequest.PropertyDependencies"
    urns::Vector{String}
end
PB.default_values(::Type{var"RegisterResourceRequest.PropertyDependencies"}) = (;urns = Vector{String}())
PB.field_numbers(::Type{var"RegisterResourceRequest.PropertyDependencies"}) = (;urns = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"RegisterResourceRequest.PropertyDependencies"})
    urns = PB.BufferedVector{String}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, urns)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"RegisterResourceRequest.PropertyDependencies"(urns[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"RegisterResourceRequest.PropertyDependencies")
    initpos = position(e.io)
    !isempty(x.urns) && PB.encode(e, 1, x.urns)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"RegisterResourceRequest.PropertyDependencies")
    encoded_size = 0
    !isempty(x.urns) && (encoded_size += PB._encoded_size(x.urns, 1))
    return encoded_size
end

struct var"RegisterResourceRequest.CustomTimeouts"
    create::String
    update::String
    delete::String
end
PB.default_values(::Type{var"RegisterResourceRequest.CustomTimeouts"}) = (;create = "", update = "", delete = "")
PB.field_numbers(::Type{var"RegisterResourceRequest.CustomTimeouts"}) = (;create = 1, update = 2, delete = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:var"RegisterResourceRequest.CustomTimeouts"})
    create = ""
    update = ""
    delete = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            create = PB.decode(d, String)
        elseif field_number == 2
            update = PB.decode(d, String)
        elseif field_number == 3
            delete = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return var"RegisterResourceRequest.CustomTimeouts"(create, update, delete)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::var"RegisterResourceRequest.CustomTimeouts")
    initpos = position(e.io)
    !isempty(x.create) && PB.encode(e, 1, x.create)
    !isempty(x.update) && PB.encode(e, 2, x.update)
    !isempty(x.delete) && PB.encode(e, 3, x.delete)
    return position(e.io) - initpos
end
function PB._encoded_size(x::var"RegisterResourceRequest.CustomTimeouts")
    encoded_size = 0
    !isempty(x.create) && (encoded_size += PB._encoded_size(x.create, 1))
    !isempty(x.update) && (encoded_size += PB._encoded_size(x.update, 2))
    !isempty(x.delete) && (encoded_size += PB._encoded_size(x.delete, 3))
    return encoded_size
end

struct TransformInvokeOptions
    provider::String
    plugin_download_url::String
    version::String
    plugin_checksums::Dict{String,Vector{UInt8}}
end
PB.default_values(::Type{TransformInvokeOptions}) = (;provider = "", plugin_download_url = "", version = "", plugin_checksums = Dict{String,Vector{UInt8}}())
PB.field_numbers(::Type{TransformInvokeOptions}) = (;provider = 1, plugin_download_url = 2, version = 3, plugin_checksums = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TransformInvokeOptions})
    provider = ""
    plugin_download_url = ""
    version = ""
    plugin_checksums = Dict{String,Vector{UInt8}}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            provider = PB.decode(d, String)
        elseif field_number == 2
            plugin_download_url = PB.decode(d, String)
        elseif field_number == 3
            version = PB.decode(d, String)
        elseif field_number == 4
            PB.decode!(d, plugin_checksums)
        else
            Base.skip(d, wire_type)
        end
    end
    return TransformInvokeOptions(provider, plugin_download_url, version, plugin_checksums)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TransformInvokeOptions)
    initpos = position(e.io)
    !isempty(x.provider) && PB.encode(e, 1, x.provider)
    !isempty(x.plugin_download_url) && PB.encode(e, 2, x.plugin_download_url)
    !isempty(x.version) && PB.encode(e, 3, x.version)
    !isempty(x.plugin_checksums) && PB.encode(e, 4, x.plugin_checksums)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TransformInvokeOptions)
    encoded_size = 0
    !isempty(x.provider) && (encoded_size += PB._encoded_size(x.provider, 1))
    !isempty(x.plugin_download_url) && (encoded_size += PB._encoded_size(x.plugin_download_url, 2))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 3))
    !isempty(x.plugin_checksums) && (encoded_size += PB._encoded_size(x.plugin_checksums, 4))
    return encoded_size
end

struct RegisterPackageRequest
    name::String
    version::String
    download_url::String
    checksums::Dict{String,Vector{UInt8}}
    parameterization::Union{Nothing,Parameterization}
end
PB.default_values(::Type{RegisterPackageRequest}) = (;name = "", version = "", download_url = "", checksums = Dict{String,Vector{UInt8}}(), parameterization = nothing)
PB.field_numbers(::Type{RegisterPackageRequest}) = (;name = 1, version = 2, download_url = 3, checksums = 4, parameterization = 5)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RegisterPackageRequest})
    name = ""
    version = ""
    download_url = ""
    checksums = Dict{String,Vector{UInt8}}()
    parameterization = Ref{Union{Nothing,Parameterization}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            version = PB.decode(d, String)
        elseif field_number == 3
            download_url = PB.decode(d, String)
        elseif field_number == 4
            PB.decode!(d, checksums)
        elseif field_number == 5
            PB.decode!(d, parameterization)
        else
            Base.skip(d, wire_type)
        end
    end
    return RegisterPackageRequest(name, version, download_url, checksums, parameterization[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RegisterPackageRequest)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isempty(x.version) && PB.encode(e, 2, x.version)
    !isempty(x.download_url) && PB.encode(e, 3, x.download_url)
    !isempty(x.checksums) && PB.encode(e, 4, x.checksums)
    !isnothing(x.parameterization) && PB.encode(e, 5, x.parameterization)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RegisterPackageRequest)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 2))
    !isempty(x.download_url) && (encoded_size += PB._encoded_size(x.download_url, 3))
    !isempty(x.checksums) && (encoded_size += PB._encoded_size(x.checksums, 4))
    !isnothing(x.parameterization) && (encoded_size += PB._encoded_size(x.parameterization, 5))
    return encoded_size
end

struct ResourceCallRequest
    tok::String
    args::Union{Nothing,google.protobuf.Struct}
    argDependencies::Dict{String,var"ResourceCallRequest.ArgumentDependencies"}
    provider::String
    version::String
    pluginDownloadURL::String
    pluginChecksums::Dict{String,Vector{UInt8}}
    sourcePosition::Union{Nothing,SourcePosition}
    stackTrace::Union{Nothing,StackTrace}
    parentStackTraceHandle::String
    packageRef::String
end
PB.reserved_fields(::Type{ResourceCallRequest}) = (names = ["project", "stack", "config", "configSecretKeys", "dryRun", "parallel", "monitorEndpoint", "organization"], numbers = Union{Int,UnitRange{Int}}[6, 7, 8, 9, 10, 11, 12, 14])
PB.default_values(::Type{ResourceCallRequest}) = (;tok = "", args = nothing, argDependencies = Dict{String,var"ResourceCallRequest.ArgumentDependencies"}(), provider = "", version = "", pluginDownloadURL = "", pluginChecksums = Dict{String,Vector{UInt8}}(), sourcePosition = nothing, stackTrace = nothing, parentStackTraceHandle = "", packageRef = "")
PB.field_numbers(::Type{ResourceCallRequest}) = (;tok = 1, args = 2, argDependencies = 3, provider = 4, version = 5, pluginDownloadURL = 13, pluginChecksums = 16, sourcePosition = 15, stackTrace = 18, parentStackTraceHandle = 19, packageRef = 17)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ResourceCallRequest})
    tok = ""
    args = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    argDependencies = Dict{String,var"ResourceCallRequest.ArgumentDependencies"}()
    provider = ""
    version = ""
    pluginDownloadURL = ""
    pluginChecksums = Dict{String,Vector{UInt8}}()
    sourcePosition = Ref{Union{Nothing,SourcePosition}}(nothing)
    stackTrace = Ref{Union{Nothing,StackTrace}}(nothing)
    parentStackTraceHandle = ""
    packageRef = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            tok = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, args)
        elseif field_number == 3
            PB.decode!(d, argDependencies)
        elseif field_number == 4
            provider = PB.decode(d, String)
        elseif field_number == 5
            version = PB.decode(d, String)
        elseif field_number == 13
            pluginDownloadURL = PB.decode(d, String)
        elseif field_number == 16
            PB.decode!(d, pluginChecksums)
        elseif field_number == 15
            PB.decode!(d, sourcePosition)
        elseif field_number == 18
            PB.decode!(d, stackTrace)
        elseif field_number == 19
            parentStackTraceHandle = PB.decode(d, String)
        elseif field_number == 17
            packageRef = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return ResourceCallRequest(tok, args[], argDependencies, provider, version, pluginDownloadURL, pluginChecksums, sourcePosition[], stackTrace[], parentStackTraceHandle, packageRef)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ResourceCallRequest)
    initpos = position(e.io)
    !isempty(x.tok) && PB.encode(e, 1, x.tok)
    !isnothing(x.args) && PB.encode(e, 2, x.args)
    !isempty(x.argDependencies) && PB.encode(e, 3, x.argDependencies)
    !isempty(x.provider) && PB.encode(e, 4, x.provider)
    !isempty(x.version) && PB.encode(e, 5, x.version)
    !isempty(x.pluginDownloadURL) && PB.encode(e, 13, x.pluginDownloadURL)
    !isempty(x.pluginChecksums) && PB.encode(e, 16, x.pluginChecksums)
    !isnothing(x.sourcePosition) && PB.encode(e, 15, x.sourcePosition)
    !isnothing(x.stackTrace) && PB.encode(e, 18, x.stackTrace)
    !isempty(x.parentStackTraceHandle) && PB.encode(e, 19, x.parentStackTraceHandle)
    !isempty(x.packageRef) && PB.encode(e, 17, x.packageRef)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ResourceCallRequest)
    encoded_size = 0
    !isempty(x.tok) && (encoded_size += PB._encoded_size(x.tok, 1))
    !isnothing(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    !isempty(x.argDependencies) && (encoded_size += PB._encoded_size(x.argDependencies, 3))
    !isempty(x.provider) && (encoded_size += PB._encoded_size(x.provider, 4))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 5))
    !isempty(x.pluginDownloadURL) && (encoded_size += PB._encoded_size(x.pluginDownloadURL, 13))
    !isempty(x.pluginChecksums) && (encoded_size += PB._encoded_size(x.pluginChecksums, 16))
    !isnothing(x.sourcePosition) && (encoded_size += PB._encoded_size(x.sourcePosition, 15))
    !isnothing(x.stackTrace) && (encoded_size += PB._encoded_size(x.stackTrace, 18))
    !isempty(x.parentStackTraceHandle) && (encoded_size += PB._encoded_size(x.parentStackTraceHandle, 19))
    !isempty(x.packageRef) && (encoded_size += PB._encoded_size(x.packageRef, 17))
    return encoded_size
end

struct RegisterResourceResponse
    urn::String
    id::String
    object::Union{Nothing,google.protobuf.Struct}
    stable::Bool
    stables::Vector{String}
    propertyDependencies::Dict{String,var"RegisterResourceResponse.PropertyDependencies"}
    result::Result.T
end
PB.default_values(::Type{RegisterResourceResponse}) = (;urn = "", id = "", object = nothing, stable = false, stables = Vector{String}(), propertyDependencies = Dict{String,var"RegisterResourceResponse.PropertyDependencies"}(), result = Result.SUCCESS)
PB.field_numbers(::Type{RegisterResourceResponse}) = (;urn = 1, id = 2, object = 3, stable = 4, stables = 5, propertyDependencies = 6, result = 7)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RegisterResourceResponse})
    urn = ""
    id = ""
    object = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    stable = false
    stables = PB.BufferedVector{String}()
    propertyDependencies = Dict{String,var"RegisterResourceResponse.PropertyDependencies"}()
    result = Result.SUCCESS
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            urn = PB.decode(d, String)
        elseif field_number == 2
            id = PB.decode(d, String)
        elseif field_number == 3
            PB.decode!(d, object)
        elseif field_number == 4
            stable = PB.decode(d, Bool)
        elseif field_number == 5
            PB.decode!(d, stables)
        elseif field_number == 6
            PB.decode!(d, propertyDependencies)
        elseif field_number == 7
            result = PB.decode(d, Result.T)
        else
            Base.skip(d, wire_type)
        end
    end
    return RegisterResourceResponse(urn, id, object[], stable, stables[], propertyDependencies, result)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RegisterResourceResponse)
    initpos = position(e.io)
    !isempty(x.urn) && PB.encode(e, 1, x.urn)
    !isempty(x.id) && PB.encode(e, 2, x.id)
    !isnothing(x.object) && PB.encode(e, 3, x.object)
    x.stable != false && PB.encode(e, 4, x.stable)
    !isempty(x.stables) && PB.encode(e, 5, x.stables)
    !isempty(x.propertyDependencies) && PB.encode(e, 6, x.propertyDependencies)
    x.result != Result.SUCCESS && PB.encode(e, 7, x.result)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RegisterResourceResponse)
    encoded_size = 0
    !isempty(x.urn) && (encoded_size += PB._encoded_size(x.urn, 1))
    !isempty(x.id) && (encoded_size += PB._encoded_size(x.id, 2))
    !isnothing(x.object) && (encoded_size += PB._encoded_size(x.object, 3))
    x.stable != false && (encoded_size += PB._encoded_size(x.stable, 4))
    !isempty(x.stables) && (encoded_size += PB._encoded_size(x.stables, 5))
    !isempty(x.propertyDependencies) && (encoded_size += PB._encoded_size(x.propertyDependencies, 6))
    x.result != Result.SUCCESS && (encoded_size += PB._encoded_size(x.result, 7))
    return encoded_size
end

struct TransformResourceOptions
    depends_on::Vector{String}
    protect::Bool
    ignore_changes::Vector{String}
    replace_on_changes::Vector{String}
    version::String
    aliases::Vector{Alias}
    provider::String
    custom_timeouts::Union{Nothing,var"RegisterResourceRequest.CustomTimeouts"}
    plugin_download_url::String
    retain_on_delete::Bool
    deleted_with::String
    delete_before_replace::Bool
    additional_secret_outputs::Vector{String}
    providers::Dict{String,String}
    plugin_checksums::Dict{String,Vector{UInt8}}
    hooks::Union{Nothing,var"RegisterResourceRequest.ResourceHooksBinding"}
    var"#import"::String
    hide_diff::Vector{String}
    replace_with::Vector{String}
    replacement_trigger::Union{Nothing,google.protobuf.Value}
end
PB.default_values(::Type{TransformResourceOptions}) = (;depends_on = Vector{String}(), protect = false, ignore_changes = Vector{String}(), replace_on_changes = Vector{String}(), version = "", aliases = Vector{Alias}(), provider = "", custom_timeouts = nothing, plugin_download_url = "", retain_on_delete = false, deleted_with = "", delete_before_replace = false, additional_secret_outputs = Vector{String}(), providers = Dict{String,String}(), plugin_checksums = Dict{String,Vector{UInt8}}(), hooks = nothing, var"#import" = "", hide_diff = Vector{String}(), replace_with = Vector{String}(), replacement_trigger = nothing)
PB.field_numbers(::Type{TransformResourceOptions}) = (;depends_on = 1, protect = 2, ignore_changes = 3, replace_on_changes = 4, version = 5, aliases = 6, provider = 7, custom_timeouts = 8, plugin_download_url = 9, retain_on_delete = 10, deleted_with = 11, delete_before_replace = 12, additional_secret_outputs = 13, providers = 14, plugin_checksums = 15, hooks = 16, var"#import" = 17, hide_diff = 18, replace_with = 19, replacement_trigger = 20)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TransformResourceOptions})
    depends_on = PB.BufferedVector{String}()
    protect = false
    ignore_changes = PB.BufferedVector{String}()
    replace_on_changes = PB.BufferedVector{String}()
    version = ""
    aliases = PB.BufferedVector{Alias}()
    provider = ""
    custom_timeouts = Ref{Union{Nothing,var"RegisterResourceRequest.CustomTimeouts"}}(nothing)
    plugin_download_url = ""
    retain_on_delete = false
    deleted_with = ""
    delete_before_replace = false
    additional_secret_outputs = PB.BufferedVector{String}()
    providers = Dict{String,String}()
    plugin_checksums = Dict{String,Vector{UInt8}}()
    hooks = Ref{Union{Nothing,var"RegisterResourceRequest.ResourceHooksBinding"}}(nothing)
    var"#import" = ""
    hide_diff = PB.BufferedVector{String}()
    replace_with = PB.BufferedVector{String}()
    replacement_trigger = Ref{Union{Nothing,google.protobuf.Value}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, depends_on)
        elseif field_number == 2
            protect = PB.decode(d, Bool)
        elseif field_number == 3
            PB.decode!(d, ignore_changes)
        elseif field_number == 4
            PB.decode!(d, replace_on_changes)
        elseif field_number == 5
            version = PB.decode(d, String)
        elseif field_number == 6
            PB.decode!(d, aliases)
        elseif field_number == 7
            provider = PB.decode(d, String)
        elseif field_number == 8
            PB.decode!(d, custom_timeouts)
        elseif field_number == 9
            plugin_download_url = PB.decode(d, String)
        elseif field_number == 10
            retain_on_delete = PB.decode(d, Bool)
        elseif field_number == 11
            deleted_with = PB.decode(d, String)
        elseif field_number == 12
            delete_before_replace = PB.decode(d, Bool)
        elseif field_number == 13
            PB.decode!(d, additional_secret_outputs)
        elseif field_number == 14
            PB.decode!(d, providers)
        elseif field_number == 15
            PB.decode!(d, plugin_checksums)
        elseif field_number == 16
            PB.decode!(d, hooks)
        elseif field_number == 17
            var"#import" = PB.decode(d, String)
        elseif field_number == 18
            PB.decode!(d, hide_diff)
        elseif field_number == 19
            PB.decode!(d, replace_with)
        elseif field_number == 20
            PB.decode!(d, replacement_trigger)
        else
            Base.skip(d, wire_type)
        end
    end
    return TransformResourceOptions(depends_on[], protect, ignore_changes[], replace_on_changes[], version, aliases[], provider, custom_timeouts[], plugin_download_url, retain_on_delete, deleted_with, delete_before_replace, additional_secret_outputs[], providers, plugin_checksums, hooks[], var"#import", hide_diff[], replace_with[], replacement_trigger[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TransformResourceOptions)
    initpos = position(e.io)
    !isempty(x.depends_on) && PB.encode(e, 1, x.depends_on)
    x.protect != false && PB.encode(e, 2, x.protect)
    !isempty(x.ignore_changes) && PB.encode(e, 3, x.ignore_changes)
    !isempty(x.replace_on_changes) && PB.encode(e, 4, x.replace_on_changes)
    !isempty(x.version) && PB.encode(e, 5, x.version)
    !isempty(x.aliases) && PB.encode(e, 6, x.aliases)
    !isempty(x.provider) && PB.encode(e, 7, x.provider)
    !isnothing(x.custom_timeouts) && PB.encode(e, 8, x.custom_timeouts)
    !isempty(x.plugin_download_url) && PB.encode(e, 9, x.plugin_download_url)
    x.retain_on_delete != false && PB.encode(e, 10, x.retain_on_delete)
    !isempty(x.deleted_with) && PB.encode(e, 11, x.deleted_with)
    x.delete_before_replace != false && PB.encode(e, 12, x.delete_before_replace)
    !isempty(x.additional_secret_outputs) && PB.encode(e, 13, x.additional_secret_outputs)
    !isempty(x.providers) && PB.encode(e, 14, x.providers)
    !isempty(x.plugin_checksums) && PB.encode(e, 15, x.plugin_checksums)
    !isnothing(x.hooks) && PB.encode(e, 16, x.hooks)
    !isempty(x.var"#import") && PB.encode(e, 17, x.var"#import")
    !isempty(x.hide_diff) && PB.encode(e, 18, x.hide_diff)
    !isempty(x.replace_with) && PB.encode(e, 19, x.replace_with)
    !isnothing(x.replacement_trigger) && PB.encode(e, 20, x.replacement_trigger)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TransformResourceOptions)
    encoded_size = 0
    !isempty(x.depends_on) && (encoded_size += PB._encoded_size(x.depends_on, 1))
    x.protect != false && (encoded_size += PB._encoded_size(x.protect, 2))
    !isempty(x.ignore_changes) && (encoded_size += PB._encoded_size(x.ignore_changes, 3))
    !isempty(x.replace_on_changes) && (encoded_size += PB._encoded_size(x.replace_on_changes, 4))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 5))
    !isempty(x.aliases) && (encoded_size += PB._encoded_size(x.aliases, 6))
    !isempty(x.provider) && (encoded_size += PB._encoded_size(x.provider, 7))
    !isnothing(x.custom_timeouts) && (encoded_size += PB._encoded_size(x.custom_timeouts, 8))
    !isempty(x.plugin_download_url) && (encoded_size += PB._encoded_size(x.plugin_download_url, 9))
    x.retain_on_delete != false && (encoded_size += PB._encoded_size(x.retain_on_delete, 10))
    !isempty(x.deleted_with) && (encoded_size += PB._encoded_size(x.deleted_with, 11))
    x.delete_before_replace != false && (encoded_size += PB._encoded_size(x.delete_before_replace, 12))
    !isempty(x.additional_secret_outputs) && (encoded_size += PB._encoded_size(x.additional_secret_outputs, 13))
    !isempty(x.providers) && (encoded_size += PB._encoded_size(x.providers, 14))
    !isempty(x.plugin_checksums) && (encoded_size += PB._encoded_size(x.plugin_checksums, 15))
    !isnothing(x.hooks) && (encoded_size += PB._encoded_size(x.hooks, 16))
    !isempty(x.var"#import") && (encoded_size += PB._encoded_size(x.var"#import", 17))
    !isempty(x.hide_diff) && (encoded_size += PB._encoded_size(x.hide_diff, 18))
    !isempty(x.replace_with) && (encoded_size += PB._encoded_size(x.replace_with, 19))
    !isnothing(x.replacement_trigger) && (encoded_size += PB._encoded_size(x.replacement_trigger, 20))
    return encoded_size
end

struct RegisterResourceRequest
    var"#type"::String
    name::String
    parent::String
    custom::Bool
    object::Union{Nothing,google.protobuf.Struct}
    protect::Bool
    dependencies::Vector{String}
    provider::String
    propertyDependencies::Dict{String,var"RegisterResourceRequest.PropertyDependencies"}
    deleteBeforeReplace::Bool
    version::String
    ignoreChanges::Vector{String}
    acceptSecrets::Bool
    additionalSecretOutputs::Vector{String}
    aliasURNs::Vector{String}
    importId::String
    customTimeouts::Union{Nothing,var"RegisterResourceRequest.CustomTimeouts"}
    deleteBeforeReplaceDefined::Bool
    supportsPartialValues::Bool
    remote::Bool
    acceptResources::Bool
    providers::Dict{String,String}
    replaceOnChanges::Vector{String}
    pluginDownloadURL::String
    pluginChecksums::Dict{String,Vector{UInt8}}
    retainOnDelete::Bool
    aliases::Vector{Alias}
    deletedWith::String
    replace_with::Vector{String}
    replacement_trigger::Union{Nothing,google.protobuf.Value}
    aliasSpecs::Bool
    sourcePosition::Union{Nothing,SourcePosition}
    stackTrace::Union{Nothing,StackTrace}
    parentStackTraceHandle::String
    transforms::Vector{Callback}
    supportsResultReporting::Bool
    packageRef::String
    hooks::Union{Nothing,var"RegisterResourceRequest.ResourceHooksBinding"}
    hideDiffs::Vector{String}
end
PB.default_values(::Type{RegisterResourceRequest}) = (;var"#type" = "", name = "", parent = "", custom = false, object = nothing, protect = false, dependencies = Vector{String}(), provider = "", propertyDependencies = Dict{String,var"RegisterResourceRequest.PropertyDependencies"}(), deleteBeforeReplace = false, version = "", ignoreChanges = Vector{String}(), acceptSecrets = false, additionalSecretOutputs = Vector{String}(), aliasURNs = Vector{String}(), importId = "", customTimeouts = nothing, deleteBeforeReplaceDefined = false, supportsPartialValues = false, remote = false, acceptResources = false, providers = Dict{String,String}(), replaceOnChanges = Vector{String}(), pluginDownloadURL = "", pluginChecksums = Dict{String,Vector{UInt8}}(), retainOnDelete = false, aliases = Vector{Alias}(), deletedWith = "", replace_with = Vector{String}(), replacement_trigger = nothing, aliasSpecs = false, sourcePosition = nothing, stackTrace = nothing, parentStackTraceHandle = "", transforms = Vector{Callback}(), supportsResultReporting = false, packageRef = "", hooks = nothing, hideDiffs = Vector{String}())
PB.field_numbers(::Type{RegisterResourceRequest}) = (;var"#type" = 1, name = 2, parent = 3, custom = 4, object = 5, protect = 6, dependencies = 7, provider = 8, propertyDependencies = 9, deleteBeforeReplace = 10, version = 11, ignoreChanges = 12, acceptSecrets = 13, additionalSecretOutputs = 14, aliasURNs = 15, importId = 16, customTimeouts = 17, deleteBeforeReplaceDefined = 18, supportsPartialValues = 19, remote = 20, acceptResources = 21, providers = 22, replaceOnChanges = 23, pluginDownloadURL = 24, pluginChecksums = 30, retainOnDelete = 25, aliases = 26, deletedWith = 27, replace_with = 38, replacement_trigger = 39, aliasSpecs = 28, sourcePosition = 29, stackTrace = 35, parentStackTraceHandle = 36, transforms = 31, supportsResultReporting = 32, packageRef = 33, hooks = 34, hideDiffs = 37)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RegisterResourceRequest})
    var"#type" = ""
    name = ""
    parent = ""
    custom = false
    object = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    protect = false
    dependencies = PB.BufferedVector{String}()
    provider = ""
    propertyDependencies = Dict{String,var"RegisterResourceRequest.PropertyDependencies"}()
    deleteBeforeReplace = false
    version = ""
    ignoreChanges = PB.BufferedVector{String}()
    acceptSecrets = false
    additionalSecretOutputs = PB.BufferedVector{String}()
    aliasURNs = PB.BufferedVector{String}()
    importId = ""
    customTimeouts = Ref{Union{Nothing,var"RegisterResourceRequest.CustomTimeouts"}}(nothing)
    deleteBeforeReplaceDefined = false
    supportsPartialValues = false
    remote = false
    acceptResources = false
    providers = Dict{String,String}()
    replaceOnChanges = PB.BufferedVector{String}()
    pluginDownloadURL = ""
    pluginChecksums = Dict{String,Vector{UInt8}}()
    retainOnDelete = false
    aliases = PB.BufferedVector{Alias}()
    deletedWith = ""
    replace_with = PB.BufferedVector{String}()
    replacement_trigger = Ref{Union{Nothing,google.protobuf.Value}}(nothing)
    aliasSpecs = false
    sourcePosition = Ref{Union{Nothing,SourcePosition}}(nothing)
    stackTrace = Ref{Union{Nothing,StackTrace}}(nothing)
    parentStackTraceHandle = ""
    transforms = PB.BufferedVector{Callback}()
    supportsResultReporting = false
    packageRef = ""
    hooks = Ref{Union{Nothing,var"RegisterResourceRequest.ResourceHooksBinding"}}(nothing)
    hideDiffs = PB.BufferedVector{String}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            var"#type" = PB.decode(d, String)
        elseif field_number == 2
            name = PB.decode(d, String)
        elseif field_number == 3
            parent = PB.decode(d, String)
        elseif field_number == 4
            custom = PB.decode(d, Bool)
        elseif field_number == 5
            PB.decode!(d, object)
        elseif field_number == 6
            protect = PB.decode(d, Bool)
        elseif field_number == 7
            PB.decode!(d, dependencies)
        elseif field_number == 8
            provider = PB.decode(d, String)
        elseif field_number == 9
            PB.decode!(d, propertyDependencies)
        elseif field_number == 10
            deleteBeforeReplace = PB.decode(d, Bool)
        elseif field_number == 11
            version = PB.decode(d, String)
        elseif field_number == 12
            PB.decode!(d, ignoreChanges)
        elseif field_number == 13
            acceptSecrets = PB.decode(d, Bool)
        elseif field_number == 14
            PB.decode!(d, additionalSecretOutputs)
        elseif field_number == 15
            PB.decode!(d, aliasURNs)
        elseif field_number == 16
            importId = PB.decode(d, String)
        elseif field_number == 17
            PB.decode!(d, customTimeouts)
        elseif field_number == 18
            deleteBeforeReplaceDefined = PB.decode(d, Bool)
        elseif field_number == 19
            supportsPartialValues = PB.decode(d, Bool)
        elseif field_number == 20
            remote = PB.decode(d, Bool)
        elseif field_number == 21
            acceptResources = PB.decode(d, Bool)
        elseif field_number == 22
            PB.decode!(d, providers)
        elseif field_number == 23
            PB.decode!(d, replaceOnChanges)
        elseif field_number == 24
            pluginDownloadURL = PB.decode(d, String)
        elseif field_number == 30
            PB.decode!(d, pluginChecksums)
        elseif field_number == 25
            retainOnDelete = PB.decode(d, Bool)
        elseif field_number == 26
            PB.decode!(d, aliases)
        elseif field_number == 27
            deletedWith = PB.decode(d, String)
        elseif field_number == 38
            PB.decode!(d, replace_with)
        elseif field_number == 39
            PB.decode!(d, replacement_trigger)
        elseif field_number == 28
            aliasSpecs = PB.decode(d, Bool)
        elseif field_number == 29
            PB.decode!(d, sourcePosition)
        elseif field_number == 35
            PB.decode!(d, stackTrace)
        elseif field_number == 36
            parentStackTraceHandle = PB.decode(d, String)
        elseif field_number == 31
            PB.decode!(d, transforms)
        elseif field_number == 32
            supportsResultReporting = PB.decode(d, Bool)
        elseif field_number == 33
            packageRef = PB.decode(d, String)
        elseif field_number == 34
            PB.decode!(d, hooks)
        elseif field_number == 37
            PB.decode!(d, hideDiffs)
        else
            Base.skip(d, wire_type)
        end
    end
    return RegisterResourceRequest(var"#type", name, parent, custom, object[], protect, dependencies[], provider, propertyDependencies, deleteBeforeReplace, version, ignoreChanges[], acceptSecrets, additionalSecretOutputs[], aliasURNs[], importId, customTimeouts[], deleteBeforeReplaceDefined, supportsPartialValues, remote, acceptResources, providers, replaceOnChanges[], pluginDownloadURL, pluginChecksums, retainOnDelete, aliases[], deletedWith, replace_with[], replacement_trigger[], aliasSpecs, sourcePosition[], stackTrace[], parentStackTraceHandle, transforms[], supportsResultReporting, packageRef, hooks[], hideDiffs[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RegisterResourceRequest)
    initpos = position(e.io)
    !isempty(x.var"#type") && PB.encode(e, 1, x.var"#type")
    !isempty(x.name) && PB.encode(e, 2, x.name)
    !isempty(x.parent) && PB.encode(e, 3, x.parent)
    x.custom != false && PB.encode(e, 4, x.custom)
    !isnothing(x.object) && PB.encode(e, 5, x.object)
    x.protect != false && PB.encode(e, 6, x.protect)
    !isempty(x.dependencies) && PB.encode(e, 7, x.dependencies)
    !isempty(x.provider) && PB.encode(e, 8, x.provider)
    !isempty(x.propertyDependencies) && PB.encode(e, 9, x.propertyDependencies)
    x.deleteBeforeReplace != false && PB.encode(e, 10, x.deleteBeforeReplace)
    !isempty(x.version) && PB.encode(e, 11, x.version)
    !isempty(x.ignoreChanges) && PB.encode(e, 12, x.ignoreChanges)
    x.acceptSecrets != false && PB.encode(e, 13, x.acceptSecrets)
    !isempty(x.additionalSecretOutputs) && PB.encode(e, 14, x.additionalSecretOutputs)
    !isempty(x.aliasURNs) && PB.encode(e, 15, x.aliasURNs)
    !isempty(x.importId) && PB.encode(e, 16, x.importId)
    !isnothing(x.customTimeouts) && PB.encode(e, 17, x.customTimeouts)
    x.deleteBeforeReplaceDefined != false && PB.encode(e, 18, x.deleteBeforeReplaceDefined)
    x.supportsPartialValues != false && PB.encode(e, 19, x.supportsPartialValues)
    x.remote != false && PB.encode(e, 20, x.remote)
    x.acceptResources != false && PB.encode(e, 21, x.acceptResources)
    !isempty(x.providers) && PB.encode(e, 22, x.providers)
    !isempty(x.replaceOnChanges) && PB.encode(e, 23, x.replaceOnChanges)
    !isempty(x.pluginDownloadURL) && PB.encode(e, 24, x.pluginDownloadURL)
    !isempty(x.pluginChecksums) && PB.encode(e, 30, x.pluginChecksums)
    x.retainOnDelete != false && PB.encode(e, 25, x.retainOnDelete)
    !isempty(x.aliases) && PB.encode(e, 26, x.aliases)
    !isempty(x.deletedWith) && PB.encode(e, 27, x.deletedWith)
    !isempty(x.replace_with) && PB.encode(e, 38, x.replace_with)
    !isnothing(x.replacement_trigger) && PB.encode(e, 39, x.replacement_trigger)
    x.aliasSpecs != false && PB.encode(e, 28, x.aliasSpecs)
    !isnothing(x.sourcePosition) && PB.encode(e, 29, x.sourcePosition)
    !isnothing(x.stackTrace) && PB.encode(e, 35, x.stackTrace)
    !isempty(x.parentStackTraceHandle) && PB.encode(e, 36, x.parentStackTraceHandle)
    !isempty(x.transforms) && PB.encode(e, 31, x.transforms)
    x.supportsResultReporting != false && PB.encode(e, 32, x.supportsResultReporting)
    !isempty(x.packageRef) && PB.encode(e, 33, x.packageRef)
    !isnothing(x.hooks) && PB.encode(e, 34, x.hooks)
    !isempty(x.hideDiffs) && PB.encode(e, 37, x.hideDiffs)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RegisterResourceRequest)
    encoded_size = 0
    !isempty(x.var"#type") && (encoded_size += PB._encoded_size(x.var"#type", 1))
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 2))
    !isempty(x.parent) && (encoded_size += PB._encoded_size(x.parent, 3))
    x.custom != false && (encoded_size += PB._encoded_size(x.custom, 4))
    !isnothing(x.object) && (encoded_size += PB._encoded_size(x.object, 5))
    x.protect != false && (encoded_size += PB._encoded_size(x.protect, 6))
    !isempty(x.dependencies) && (encoded_size += PB._encoded_size(x.dependencies, 7))
    !isempty(x.provider) && (encoded_size += PB._encoded_size(x.provider, 8))
    !isempty(x.propertyDependencies) && (encoded_size += PB._encoded_size(x.propertyDependencies, 9))
    x.deleteBeforeReplace != false && (encoded_size += PB._encoded_size(x.deleteBeforeReplace, 10))
    !isempty(x.version) && (encoded_size += PB._encoded_size(x.version, 11))
    !isempty(x.ignoreChanges) && (encoded_size += PB._encoded_size(x.ignoreChanges, 12))
    x.acceptSecrets != false && (encoded_size += PB._encoded_size(x.acceptSecrets, 13))
    !isempty(x.additionalSecretOutputs) && (encoded_size += PB._encoded_size(x.additionalSecretOutputs, 14))
    !isempty(x.aliasURNs) && (encoded_size += PB._encoded_size(x.aliasURNs, 15))
    !isempty(x.importId) && (encoded_size += PB._encoded_size(x.importId, 16))
    !isnothing(x.customTimeouts) && (encoded_size += PB._encoded_size(x.customTimeouts, 17))
    x.deleteBeforeReplaceDefined != false && (encoded_size += PB._encoded_size(x.deleteBeforeReplaceDefined, 18))
    x.supportsPartialValues != false && (encoded_size += PB._encoded_size(x.supportsPartialValues, 19))
    x.remote != false && (encoded_size += PB._encoded_size(x.remote, 20))
    x.acceptResources != false && (encoded_size += PB._encoded_size(x.acceptResources, 21))
    !isempty(x.providers) && (encoded_size += PB._encoded_size(x.providers, 22))
    !isempty(x.replaceOnChanges) && (encoded_size += PB._encoded_size(x.replaceOnChanges, 23))
    !isempty(x.pluginDownloadURL) && (encoded_size += PB._encoded_size(x.pluginDownloadURL, 24))
    !isempty(x.pluginChecksums) && (encoded_size += PB._encoded_size(x.pluginChecksums, 30))
    x.retainOnDelete != false && (encoded_size += PB._encoded_size(x.retainOnDelete, 25))
    !isempty(x.aliases) && (encoded_size += PB._encoded_size(x.aliases, 26))
    !isempty(x.deletedWith) && (encoded_size += PB._encoded_size(x.deletedWith, 27))
    !isempty(x.replace_with) && (encoded_size += PB._encoded_size(x.replace_with, 38))
    !isnothing(x.replacement_trigger) && (encoded_size += PB._encoded_size(x.replacement_trigger, 39))
    x.aliasSpecs != false && (encoded_size += PB._encoded_size(x.aliasSpecs, 28))
    !isnothing(x.sourcePosition) && (encoded_size += PB._encoded_size(x.sourcePosition, 29))
    !isnothing(x.stackTrace) && (encoded_size += PB._encoded_size(x.stackTrace, 35))
    !isempty(x.parentStackTraceHandle) && (encoded_size += PB._encoded_size(x.parentStackTraceHandle, 36))
    !isempty(x.transforms) && (encoded_size += PB._encoded_size(x.transforms, 31))
    x.supportsResultReporting != false && (encoded_size += PB._encoded_size(x.supportsResultReporting, 32))
    !isempty(x.packageRef) && (encoded_size += PB._encoded_size(x.packageRef, 33))
    !isnothing(x.hooks) && (encoded_size += PB._encoded_size(x.hooks, 34))
    !isempty(x.hideDiffs) && (encoded_size += PB._encoded_size(x.hideDiffs, 37))
    return encoded_size
end

struct TransformInvokeResponse
    args::Union{Nothing,google.protobuf.Struct}
    options::Union{Nothing,TransformInvokeOptions}
end
PB.default_values(::Type{TransformInvokeResponse}) = (;args = nothing, options = nothing)
PB.field_numbers(::Type{TransformInvokeResponse}) = (;args = 1, options = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TransformInvokeResponse})
    args = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    options = Ref{Union{Nothing,TransformInvokeOptions}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, args)
        elseif field_number == 2
            PB.decode!(d, options)
        else
            Base.skip(d, wire_type)
        end
    end
    return TransformInvokeResponse(args[], options[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TransformInvokeResponse)
    initpos = position(e.io)
    !isnothing(x.args) && PB.encode(e, 1, x.args)
    !isnothing(x.options) && PB.encode(e, 2, x.options)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TransformInvokeResponse)
    encoded_size = 0
    !isnothing(x.args) && (encoded_size += PB._encoded_size(x.args, 1))
    !isnothing(x.options) && (encoded_size += PB._encoded_size(x.options, 2))
    return encoded_size
end

struct TransformInvokeRequest
    token::String
    args::Union{Nothing,google.protobuf.Struct}
    options::Union{Nothing,TransformInvokeOptions}
end
PB.default_values(::Type{TransformInvokeRequest}) = (;token = "", args = nothing, options = nothing)
PB.field_numbers(::Type{TransformInvokeRequest}) = (;token = 1, args = 2, options = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TransformInvokeRequest})
    token = ""
    args = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    options = Ref{Union{Nothing,TransformInvokeOptions}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            token = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, args)
        elseif field_number == 3
            PB.decode!(d, options)
        else
            Base.skip(d, wire_type)
        end
    end
    return TransformInvokeRequest(token, args[], options[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TransformInvokeRequest)
    initpos = position(e.io)
    !isempty(x.token) && PB.encode(e, 1, x.token)
    !isnothing(x.args) && PB.encode(e, 2, x.args)
    !isnothing(x.options) && PB.encode(e, 3, x.options)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TransformInvokeRequest)
    encoded_size = 0
    !isempty(x.token) && (encoded_size += PB._encoded_size(x.token, 1))
    !isnothing(x.args) && (encoded_size += PB._encoded_size(x.args, 2))
    !isnothing(x.options) && (encoded_size += PB._encoded_size(x.options, 3))
    return encoded_size
end

# TODO: SERVICE
#    ResourceMonitor

struct TransformResponse
    properties::Union{Nothing,google.protobuf.Struct}
    options::Union{Nothing,TransformResourceOptions}
end
PB.default_values(::Type{TransformResponse}) = (;properties = nothing, options = nothing)
PB.field_numbers(::Type{TransformResponse}) = (;properties = 1, options = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TransformResponse})
    properties = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    options = Ref{Union{Nothing,TransformResourceOptions}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, properties)
        elseif field_number == 2
            PB.decode!(d, options)
        else
            Base.skip(d, wire_type)
        end
    end
    return TransformResponse(properties[], options[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TransformResponse)
    initpos = position(e.io)
    !isnothing(x.properties) && PB.encode(e, 1, x.properties)
    !isnothing(x.options) && PB.encode(e, 2, x.options)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TransformResponse)
    encoded_size = 0
    !isnothing(x.properties) && (encoded_size += PB._encoded_size(x.properties, 1))
    !isnothing(x.options) && (encoded_size += PB._encoded_size(x.options, 2))
    return encoded_size
end

struct TransformRequest
    var"#type"::String
    name::String
    custom::Bool
    parent::String
    properties::Union{Nothing,google.protobuf.Struct}
    options::Union{Nothing,TransformResourceOptions}
end
PB.default_values(::Type{TransformRequest}) = (;var"#type" = "", name = "", custom = false, parent = "", properties = nothing, options = nothing)
PB.field_numbers(::Type{TransformRequest}) = (;var"#type" = 1, name = 2, custom = 3, parent = 4, properties = 5, options = 6)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:TransformRequest})
    var"#type" = ""
    name = ""
    custom = false
    parent = ""
    properties = Ref{Union{Nothing,google.protobuf.Struct}}(nothing)
    options = Ref{Union{Nothing,TransformResourceOptions}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            var"#type" = PB.decode(d, String)
        elseif field_number == 2
            name = PB.decode(d, String)
        elseif field_number == 3
            custom = PB.decode(d, Bool)
        elseif field_number == 4
            parent = PB.decode(d, String)
        elseif field_number == 5
            PB.decode!(d, properties)
        elseif field_number == 6
            PB.decode!(d, options)
        else
            Base.skip(d, wire_type)
        end
    end
    return TransformRequest(var"#type", name, custom, parent, properties[], options[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::TransformRequest)
    initpos = position(e.io)
    !isempty(x.var"#type") && PB.encode(e, 1, x.var"#type")
    !isempty(x.name) && PB.encode(e, 2, x.name)
    x.custom != false && PB.encode(e, 3, x.custom)
    !isempty(x.parent) && PB.encode(e, 4, x.parent)
    !isnothing(x.properties) && PB.encode(e, 5, x.properties)
    !isnothing(x.options) && PB.encode(e, 6, x.options)
    return position(e.io) - initpos
end
function PB._encoded_size(x::TransformRequest)
    encoded_size = 0
    !isempty(x.var"#type") && (encoded_size += PB._encoded_size(x.var"#type", 1))
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 2))
    x.custom != false && (encoded_size += PB._encoded_size(x.custom, 3))
    !isempty(x.parent) && (encoded_size += PB._encoded_size(x.parent, 4))
    !isnothing(x.properties) && (encoded_size += PB._encoded_size(x.properties, 5))
    !isnothing(x.options) && (encoded_size += PB._encoded_size(x.options, 6))
    return encoded_size
end
