# Autogenerated using ProtoBuf.jl v1.2.0 on 2026-01-10T10:28:32.685
# original file: /home/scelles-admin/.julia/dev/Pulumi/proto/pulumi/source.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export SourcePosition, StackFrame, StackTrace


struct SourcePosition
    uri::String
    line::Int32
    column::Int32
end
PB.default_values(::Type{SourcePosition}) = (;uri = "", line = zero(Int32), column = zero(Int32))
PB.field_numbers(::Type{SourcePosition}) = (;uri = 1, line = 2, column = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:SourcePosition})
    uri = ""
    line = zero(Int32)
    column = zero(Int32)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            uri = PB.decode(d, String)
        elseif field_number == 2
            line = PB.decode(d, Int32)
        elseif field_number == 3
            column = PB.decode(d, Int32)
        else
            Base.skip(d, wire_type)
        end
    end
    return SourcePosition(uri, line, column)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::SourcePosition)
    initpos = position(e.io)
    !isempty(x.uri) && PB.encode(e, 1, x.uri)
    x.line != zero(Int32) && PB.encode(e, 2, x.line)
    x.column != zero(Int32) && PB.encode(e, 3, x.column)
    return position(e.io) - initpos
end
function PB._encoded_size(x::SourcePosition)
    encoded_size = 0
    !isempty(x.uri) && (encoded_size += PB._encoded_size(x.uri, 1))
    x.line != zero(Int32) && (encoded_size += PB._encoded_size(x.line, 2))
    x.column != zero(Int32) && (encoded_size += PB._encoded_size(x.column, 3))
    return encoded_size
end

struct StackFrame
    pc::Union{Nothing,SourcePosition}
end
PB.default_values(::Type{StackFrame}) = (;pc = nothing)
PB.field_numbers(::Type{StackFrame}) = (;pc = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:StackFrame})
    pc = Ref{Union{Nothing,SourcePosition}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, pc)
        else
            Base.skip(d, wire_type)
        end
    end
    return StackFrame(pc[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::StackFrame)
    initpos = position(e.io)
    !isnothing(x.pc) && PB.encode(e, 1, x.pc)
    return position(e.io) - initpos
end
function PB._encoded_size(x::StackFrame)
    encoded_size = 0
    !isnothing(x.pc) && (encoded_size += PB._encoded_size(x.pc, 1))
    return encoded_size
end

struct StackTrace
    frames::Vector{StackFrame}
end
PB.default_values(::Type{StackTrace}) = (;frames = Vector{StackFrame}())
PB.field_numbers(::Type{StackTrace}) = (;frames = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:StackTrace})
    frames = PB.BufferedVector{StackFrame}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, frames)
        else
            Base.skip(d, wire_type)
        end
    end
    return StackTrace(frames[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::StackTrace)
    initpos = position(e.io)
    !isempty(x.frames) && PB.encode(e, 1, x.frames)
    return position(e.io) - initpos
end
function PB._encoded_size(x::StackTrace)
    encoded_size = 0
    !isempty(x.frames) && (encoded_size += PB._encoded_size(x.frames, 1))
    return encoded_size
end
